apiVersion: v1      
kind: PersistentVolumeClaim      
metadata:      
  name: ingress-nfs      
  namespace: ingress-nginx
spec:      
  accessModes:      
  - ReadWriteMany      
  resources:      
    requests:      
      storage: 10Gi      
  storageClassName: normal-nfs-storage