kind:  ConfigMap
apiVersion:  v1
metadata: 
  name:  nginx-configuration
  namespace:  ingress-nginx
  labels: 
    app.kubernetes.io/name:  ingress-nginx
    app.kubernetes.io/part-of:  ingress-nginx
data:
  log-format-escape-json: "true"
  log-format-upstream: |-
    {
        "remote_addr":"$remote_addr",
        "remote_port":"$remote_port",
        "http_x_forwarded_for":"$http_x_forwarded_for",
        "time_local":"$time_local",'
        "server_protocol":"$server_protocol",
        "request_method":"$request_method",'
        "scheme":"$scheme",
        "host":"$host",
        "request_uri":"$request_uri",
        "url":"$scheme://$host$request_uri",
        "status":"$status",
        "body_bytes_sent":"$body_bytes_sent",
        "request_time":"$request_time",
        "http_referer":"$http_referer",
        "http_user_agent":"$http_user_agent",
        "upstream_addr":"$upstream_addr",
        "upstream_response_time":"$upstream_response_time",
        "upstream_status":"$upstream_status"
    }
  client_max_body_size: "2000m"
  