apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: ops-monit
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "normal-nfs-storage"