apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: ops-monit
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: "normal-nfs-storage"