apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ops-monit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: webui
      port: 9090
      targetPort: 9090
      protocol: TCP